version: '3.7'

services:

  archivos: 
    image: ejramirezs/archivos:v1
    container_name: archivos
    ports:
      - 4000:4000
    restart: always
    volumes:
    # - /Users/enrique/Documents/INTRAFAD/RAID0/archivos/data:/data/
     - /media/uepa/DATA/INTRAFAD/archivos/data:/data/ 
    environment:
      PORT: 4000
      NODE_ENV: "production"


  datosPersonales: 
    image: ejramirezs/datospersonales:v1
    container_name: datosPersonales
    ports:
      - 3000:3000
    restart: always
    volumes:
    #  - /Users/enrique/Documents/INTRAFAD/RAID0/datosPersonales/data:/data/
      - /media/uepa/DATA/INTRAFAD/datosPersonales/data:/data/ 
    environment:
      PORT: 3000
      URIDB: "mongodb://mongoAdmin:AdminFAD@mongoDatosPersonales:27017/"
      NODE_ENV: "production"

  mongoDatosPersonales:
    image: mongo
    restart: always
    container_name: mongoDatosPersonales
    volumes:
    #  - /Users/enrique/Documents/INTRAFAD/RAID0/datosPersonales/db/:/data/db
      - /media/uepa/DATA/INTRAFAD/datosPersonales/db:/data/db 
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: AdminFAD
      MONGO_INITDB_DATABASE: datosPersonales